type: LoopWorkflow

researcher:
  agent_config: researcher.yaml

planner:
  agent_config: planner.yaml
  
loop:
  coder:
    agent_config: coder.yaml
    breaker: false

  refiner:
    agent_config: refiner.yaml
    breaker: true