research:
  next:
    - coding
  agent_config: research.yaml
  description: 
    Research about the problem and design the algorithm.

coding:
  next:
    - structure_arrange
    - research
  agent_config: coding.yaml
  description: 
    Implement the code to solve the problem step by step.

structure_arrange:
  next:
    - refine
  agent_config: structure_arrange.yaml
  description: 
    Arrange the code structure to make the project more organized and easier to understand.

refine:
  next:
    - exit
    - coding
  agent_config: refine.yaml
  description: 
    Test and debug the code until it works correctly based on the information in analysis.md.

exit:
  description: 
    Exit the task when all the code works correctly.

  