generate_script:
  agent_config: "agent.yaml"
  agent:
    kwargs:
      code_file: step1_generate_script/agent.py
  next:
    - segment

segment:
  agent:
    kwargs:
      code_file: step2_segment/agent.py
  next:
    - generate_audio

generate_audio:
  agent:
    kwargs:
      code_file: step3_generate_audio/agent.py
  next:
    - generate_manim_code

generate_manim_code:
  agent:
    kwargs:
      code_file: step4_generate_manim_code/agent.py
  next:
    - fix_manim_code

fix_manim_code:
  agent:
    kwargs:
      code_file: step5_fix_manim_code/agent.py
  next:
    - render_manim

render_manim:
  agent:
    kwargs:
      code_file: step6_render_manim/agent.py
  next:
    - generate_illustration_prompts

generate_illustration_prompts:
  agent:
    kwargs:
      code_file: step7_generate_illustration_prompts/agent.py
  next:
    - generate_images

generate_images:
  agent:
    kwargs:
      code_file: step8_generate_images/agent.py
  next:
    - generate_subtitle

generate_subtitle:
  agent:
    kwargs:
      code_file: step9_generate_subtitle/agent.py
  next:
    - create_background

create_background:
  agent:
    kwargs:
      code_file: step10_create_background/agent.py
  next:
    - compose_video

compose_video:
  agent:
    kwargs:
      code_file: step11_compose_video/agent.py
  next:
    - human_feedback

human_feedback:
  agent:
    kwargs:
      code_file: step12_human_feedback/agent.py
