research:
  next:
    - architecture
  agent_config: research.yaml

architecture:
  next:
    - coding
  agent_config: architecture.yaml


coding:
  next:
    - refine
  agent_config: coding.yaml


refine:
  agent_config: refine.yaml
